#!/bin/bash

while true
do
    cur="$(iptables -t filter -L f2b-sshd -n -v)"
    if [ "$cur" != "$later" -a -n "$later" ]; then
        echo -e "\n\n----------------"`date`"-----------"
        diff -u -0 <(echo "$later") <(echo "$cur") | grep -v "/dev/fd"
    fi
    later=$cur
    sleep 10
done
